#!/usr/bin/env python3
"""Generate a fully synthetic, visibly invalid demo of the ITR agent workflow."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
AGENT = ROOT / "itr_agent" / "itr_filing_agent.py"
DEMO = ROOT / "itr_agent" / "demo_output" / "SYNTHETIC_CLIENT_AY_2026-27"


def font(size: int, bold: bool = False):
    candidates = [
        Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/calibrib.ttf" if bold else "C:/Windows/Fonts/calibri.ttf"),
    ]
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()


def pdf_page(path: Path, title: str, lines: list[str]) -> None:
    image = Image.new("RGB", (1240, 1754), "white")
    draw = ImageDraw.Draw(image)
    red = (180, 0, 0)
    draw.rectangle((35, 35, 1205, 1719), outline=red, width=8)
    draw.text((620, 85), "SAMPLE - NOT VALID - DO NOT FILE", font=font(40, True), fill=red, anchor="ma")
    draw.text((620, 175), title, font=font(38, True), fill="black", anchor="ma")
    y = 265
    for line in lines:
        draw.text((90, y), line, font=font(25), fill="black")
        y += 48
    draw.text((620, 1640), "Synthetic test fixture generated by the reusable ITR agent", font=font(22, True), fill=red, anchor="ma")
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, "PDF", resolution=150.0)


def run(*args: str) -> None:
    result = subprocess.run([sys.executable, str(AGENT), *args], text=True, capture_output=True)
    if result.returncode not in (0, 3, 4):
        raise RuntimeError(result.stdout + result.stderr)
    print(result.stdout)


def main() -> int:
    if DEMO.exists():
        shutil.rmtree(DEMO)
    run("init", str(DEMO), "--client-id", "SYNTHETIC_CLIENT", "--regime", "old")
    extracted = DEMO / "02_extracted"
    return_data = {
        "assessment_year": "2026-27", "financial_year": "2025-26",
        "taxpayer": {"age_band": "below_60"},
        "income": {"gross_salary": 2355971, "savings_interest": 4692,
                   "other_ordinary_income": 0, "special_rate_income": 0,
                   "business_income": 0},
        "tax_paid": {"tds": 281060},
        "deductions": {"80c": 125238, "80d": 16348, "80tta": 4692,
                       "80g_eligible_deduction": 0, "80ccd2": 0},
        "warnings": ["ALL DATA IN THIS WORKSPACE IS SYNTHETIC AND MUST NOT BE FILED"],
    }
    (extracted / "return_data.json").write_text(json.dumps(return_data, indent=2), encoding="utf-8")

    evidence = DEMO / "01_source" / "deductions" / "80g"
    receipt = evidence / "SAMPLE_80G_Donation_Receipt_NOT_VALID.pdf"
    form10be = evidence / "SAMPLE_Form_10BE_NOT_VALID.pdf"
    pdf_page(receipt, "SYNTHETIC 80G DONATION RECEIPT", [
        "Donee: Synthetic Nature Lab Demo", "Dummy PAN: ABCDE1234F",
        "Dummy 80G URN: SYNTHETIC-80G-URN", "Receipt: DEMO-0001",
        "Payment date: 01 March 2026", "Mode: Bank transfer",
        "Reference: SYNTHETIC-BANK-REFERENCE", "Donation amount: Rs 2,30,000",
        "This is not issued by a real donee and creates no tax entitlement.",
    ])
    pdf_page(form10be, "SYNTHETIC FORM 10BE EVIDENCE FIXTURE", [
        "Donee: Synthetic Nature Lab Demo", "Dummy PAN: ABCDE1234F",
        "Dummy 80G URN: SYNTHETIC-80G-URN", "Donor: Synthetic Client",
        "Donation amount: Rs 2,30,000", "Category used for test: 50% with limit",
        "This is not Form 10BE and must never be uploaded or relied upon.",
    ])

    run("add-80g", str(DEMO), "--donee-name", "Synthetic Nature Lab Demo",
        "--donee-pan", "ABCDE1234F", "--donee-address", "Synthetic Demo Address",
        "--urn", "SYNTHETIC-80G-URN", "--category", "50_with_limit",
        "--amount", "230000", "--payment-date", "2026-03-01",
        "--payment-mode", "bank_transfer", "--payment-reference", "SYNTHETIC-BANK-REFERENCE",
        "--receipt-number", "DEMO-0001", "--receipt-file", str(receipt),
        "--form10be-file", str(form10be))
    run("calculate", str(DEMO))
    run("index", str(DEMO))

    comparison = json.loads((DEMO / "03_workpapers" / "tax_comparison.json").read_text())
    old = comparison["old_regime"]
    pdf_page(DEMO / "03_workpapers" / "SAMPLE_Old_Regime_Tax_Computation_NOT_VALID.pdf",
             "SYNTHETIC OLD-REGIME TAX COMPUTATION", [
        f"Gross total income: Rs {old['gross_total_income']:,}",
        f"80C deduction: Rs {old['deductions']['80C']:,}",
        f"80D deduction: Rs {old['deductions']['80D']:,}",
        f"80TTA deduction: Rs {old['deductions']['80TTA']:,}",
        f"80G deduction: Rs {old['deductions']['80G']:,}",
        f"Total Chapter VI-A deductions: Rs {old['total_deductions']:,}",
        f"Total income: Rs {old['total_income']:,}",
        f"Tax plus cess: Rs {old['total_tax_rounded_288b']:,}",
        f"TDS: Rs {old['tds']:,}", f"Balance payable: Rs {old['balance_payable']:,}",
        "This computation uses synthetic data and is not filing advice.",
    ])
    print(f"Demo generated at: {DEMO}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
